#!/bin/sh
# this hook is in SCM so that it can be shared
# to skip the tests, run with the --no-verify argument
#       i.e. - $ 'git commit --no-verify'

# stash any unstaged changes
git stash -q --keep-index

# run the checks and tests with the gradle wrapper
./gradlew check test integration

# store the last exit code in a variable
RESULT=$?

# unstash the previously stashed changes
git stash pop -q

# return the './gradlew check test' exit code
exit $RESULT
